<?php

namespace Pms\Bundle\ProjectsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamStudentRepository extends EntityRepository
{
}
